### ISSUE TITLE
Email Not Working

### ISSUE THREAD

**Issue by searnhardt** [rbiddle/phppickem#3]
The email functionality doesn't seem to be working and I'm not quite sure where to start looking.  Can you let me know config files on anywhere I might look to troubleshoot?

**Comment by searnhardt** [comment]
I'm not sure it is the best answer, but I was able to work around this by commenting the following lines in the "send_email.php" file, Basically changing the if-then to just pull the sql.  I'm assuming "ENABLE_MAILING_LIST" was true for me but I don't know where or how to change that or even check it.

} else {
		//select all users
		//SE if (ENABLE_MAILING_LIST)
			//SE $sql = "select 'everyone' as firstname, '" . MAILING_LIST . "' as email";
		//SE else
		$sql = "select firstname, email from " . DB_PREFIX . "users where `status` = 1 and userName <> 'admin'";
	}

**Comment by rbiddle** [comment]
My family doesn't use the email functionality, so I don't know that I can help here. My plan eventually was to take it out since I don't maintain that functionality.  But if anyone is using it, I'll leave it and accept any pushes made for fixes by anyone that does maintain it.
