### ISSUE TITLE
install

### ISSUE THREAD

**Issue by Blindsquirrelllc** [rbiddle/phppickem#7]
I am relatively new to all of this but,  I have made the database connection changes needed and uploaded all of the files to my server and every time I try to run the install I am getting a 404 file not found do I have the files in the wrong spot on my server or am I missing something else. any help wouldld be appreciated?

<img width="1440" alt="Screenshot 2024-08-11 at 6 59 32 PM" src="https://github.com/user-attachments/assets/3051c60f-dc5f-4975-af1e-f0b190276781">
<img width="1268" alt="Screenshot 2024-08-11 at 7 00 00 PM" src="https://github.com/user-attachments/assets/33fb2263-96c3-4d08-bef3-15d0669a4f78">

**Comment by Blindsquirrelllc** [comment]
figured it out

**Comment by tristanfleming** [comment]
> figured it out

Please share your fix. Responding "figured it out" helps no one in the future who comes across the same issue.

**Comment by rbiddle** [comment]
I'm guessing that the 404 error ended up that the files were in the wrong spot and you fixed it by moving them or updating the server config.

I'm closing the bug, but I'm trying to watch github more often for bugs (I wasn't getting notifications for the last month, so I missed this when it happened).
